name = "rbtr08"
version = "0.1.0"
license = "license"
author = "Zdenek Grof"
maintainer = "zdenek.grof@vscht.cz"
copyright = "Copyright 2022, Zdenek Grof"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
[fortran]
implicit-external = true
